version: '3'

services:
    mongo:
        image: mongo
        ports: 
        - "27017:27017"
        environment:
        - MONGO_INITDB_ROOT_USERNAME="admin"
        - MONGO_INITDB_ROOT_PASSWORD="geheim"
        - MONGO_INITDB_DATABASE="admin-db"

    mongo-customerOne:
        image: mongo
        ports: 
        - "27018:27017"
        environment:
        - MONGO_INITDB_ROOT_USERNAME="admin"
        - MONGO_INITDB_ROOT_PASSWORD="geheim"
        - MONGO_INITDB_DATABASE="admin-db"

    mongo-customerTwo:
        image: mongo
        ports: 
        - "27019:27017"
        environment:
        - MONGO_INITDB_ROOT_USERNAME="admin"
        - MONGO_INITDB_ROOT_PASSWORD="geheim"
        - MONGO_INITDB_DATABASE="admin-db"
